-- =====================================================
-- USERS TABLE
-- =====================================================
-- Drop tables in reverse order of creation to avoid foreign key constraint errors
DROP TABLE notifications CASCADE CONSTRAINTS;
DROP TABLE reposts CASCADE CONSTRAINTS;
DROP TABLE follows CASCADE CONSTRAINTS;
DROP TABLE connections CASCADE CONSTRAINTS;
DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE likes CASCADE CONSTRAINTS;
DROP TABLE posts CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR2(100) UNIQUE NOT NULL,
                       password VARCHAR2(255) NOT NULL,
                       username VARCHAR2(50) UNIQUE NOT NULL,
                       user_type VARCHAR2(20) CHECK (user_type IN ('PERSONAL','CREATOR','BUSINESS')) NOT NULL,
                       name VARCHAR2(100) NOT NULL,
                       bio VARCHAR2(500),
                       profile_picture VARCHAR2(255),
                       location VARCHAR2(100),
                       website VARCHAR2(255),
                       business_name VARCHAR2(100),
                       category VARCHAR2(50),
                       business_address VARCHAR2(500),
                       contact_info VARCHAR2(100),
                       business_hours VARCHAR2(100),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       is_private NUMBER(1) DEFAULT 0
);

-- =====================================================
-- POSTS TABLE
-- =====================================================
CREATE TABLE posts (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id NUMBER NOT NULL,
                       content VARCHAR2(500) NOT NULL,
                       hashtags VARCHAR2(500),
                       is_promotional NUMBER(1) DEFAULT 0,
                       pinned NUMBER(1) DEFAULT 0,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- LIKES TABLE
-- =====================================================
CREATE TABLE likes (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       post_id NUMBER NOT NULL,
                       user_id NUMBER NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
                       CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                       CONSTRAINT uk_like UNIQUE (post_id, user_id)
);

-- =====================================================
-- COMMENTS TABLE
-- =====================================================
CREATE TABLE comments (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          post_id NUMBER NOT NULL,
                          user_id NUMBER NOT NULL,
                          content VARCHAR2(500) NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
                          CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- CONNECTIONS TABLE
-- =====================================================
CREATE TABLE connections (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             requester_id NUMBER NOT NULL,
                             receiver_id NUMBER NOT NULL,
                             status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACCEPTED','REJECTED')),
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT fk_conn_requester FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
                             CONSTRAINT fk_conn_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
                             CONSTRAINT uk_connection UNIQUE (requester_id, receiver_id)
);

-- =====================================================
-- FOLLOWS TABLE
-- =====================================================
CREATE TABLE follows (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         follower_id NUMBER NOT NULL,
                         followed_id NUMBER NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
                         CONSTRAINT fk_follows_followed FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE,
                         CONSTRAINT uk_follow UNIQUE (follower_id, followed_id)
);

-- =====================================================
-- NOTIFICATIONS TABLE
-- =====================================================
CREATE TABLE notifications (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id NUMBER NOT NULL,
                               type VARCHAR2(50) NOT NULL,
                               title VARCHAR2(200) NOT NULL,
                               message VARCHAR2(500) NOT NULL,
                               related_id NUMBER,
                               is_read NUMBER(1) DEFAULT 0,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================
-- REPOSTS TABLE
-- =====================================================
CREATE TABLE reposts (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         original_post_id NUMBER NOT NULL,
                         user_id NUMBER NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_repost_original FOREIGN KEY (original_post_id) REFERENCES posts(id) ON DELETE CASCADE,
                         CONSTRAINT fk_repost_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                         CONSTRAINT uk_repost UNIQUE (original_post_id, user_id)
);
DROP TABLE notifications;

CREATE TABLE notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    type VARCHAR2(50) NOT NULL,
    message VARCHAR2(500) NOT NULL,
    related_id NUMBER,
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Add is_connected column to connections table if not exists
ALTER TABLE connections ADD is_connected NUMBER(1) DEFAULT 0;

-- Update existing connections to set is_connected
UPDATE connections SET is_connected = 1 WHERE status = 'ACCEPTED';

COMMIT;

-- Add status column to follows table
ALTER TABLE follows ADD status VARCHAR2(20) DEFAULT 'ACCEPTED' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'));

-- Update existing follows to have ACCEPTED status
UPDATE follows SET status = 'ACCEPTED' WHERE status IS NULL;
COMMIT;

-- Add new columns for security features
ALTER TABLE users ADD (
    security_question VARCHAR2(500),
    security_answer VARCHAR2(255),
    password_hint VARCHAR2(200),
    is_public NUMBER(1) DEFAULT 1 -- 1 = public, 0 = private
);

-- Update existing users to be public by default
UPDATE users SET is_public = 1 WHERE is_public IS NULL;
ALTER TABLE users MODIFY security_question VARCHAR2(500);
ALTER TABLE users ADD (
    business_category VARCHAR2(100),
    creator_category VARCHAR2(100)
);
COMMIT;
select * from users;

